/* KOVA — bilingual content + curated Unsplash imagery.
   Ported verbatim from the Claude Design handoff bundle (Kova Landing.html). */

export type Lang = "es" | "en";

/* Curated Unsplash imagery (premium home). Verified to load. */
export const IMG = {
  u: (id: string, w?: number) =>
    "https://images.unsplash.com/photo-" + id + "?auto=format&fit=crop&w=" + (w || 1600) + "&q=80",
  bandA: "1560448204-e02f11c3d0e2",
  bandB: "1616486338812-3dadae4b4ace",
  bandC: "1538688525198-9b88f6f53126",
  galA: "1555041469-a586c61ea9bc",
  galB: "1524758631624-e2822e304c36",
  galC: "1513161455079-7dc1de15ef3e",
  prodSofa: "1540574163026-643ea20ade25",
  prodLamp: "1522771739844-6a9f6d5f14af",
  visionRoom: "1586023492125-27b2c045efd7",
};

export const KOVA = {
  es: {
    nav: { features: "Características", how: "Cómo funciona", pricing: "Precios", faq: "FAQ", login: "Iniciar sesión", cta: "Comenzar ahora" },
    hero: {
      eyebrow: "Para tiendas de hogar premium · alto ticket",
      h1a: "Tu mejor vendedor de showroom,",
      h1em: "ahora 24/7",
      lead: "El comprador de alto ticket no decide por impulso: tiene dudas de medidas, materiales y despacho. Si nadie responde al instante, se va a “pensarlo” y no vuelve. Kova lo asesora por chat, recomienda desde tu catálogo y lo llama por teléfono para cerrar la venta.",
      cta1: "Activar mi vendedor de showroom",
      cta2: "Ver demo",
      note: "Setup en 5 minutos · 7 días de prueba · Cancela cuando quieras",
      chips: ["Llamadas con voz IA", "Carrito integrado", "Emails con recomendaciones", "Cotizaciones automáticas", "Agenda reuniones", "Recomienda por foto"],
    },
    logos: { title: "Se integra con las principales plataformas de e-commerce" },
    media: {
      bandA: { k: "El showroom, sin horario", t: "Cada pieza es una decisión de alto ticket" },
      galleryK: "El catálogo",
      galleryT: "Diseño que tu cliente quiere tocar antes de comprar",
      gallery: [{ k: "01", cap: "Muebles de diseño" }, { k: "02", cap: "Iluminación" }, { k: "03", cap: "Deco & objeto" }],
      bandB: { k: "El ambiente completo", t: "Kova entiende el espacio, no solo el producto" },
      bandC: { k: "Del “lo voy a pensar”", t: "…al checkout, en una conversación" },
    },
    voice: {
      eyebrow: "Nuevo · Voz IA",
      h: "Llamadas telefónicas reales con IA — con todo el contexto",
      lead: "Kova no solo chatea. Tu asistente atiende y realiza llamadas telefónicas reales — no VoIP, no chat de voz — a números reales. Y lo hace con todo el historial de la conversación. Sin repetir, sin fricción.",
      points: [
        { t: "Llamadas reales entrantes y salientes", d: "El agente de voz atiende y realiza llamadas a números telefónicos reales. Tus clientes llaman al número de tu tienda y Kova contesta — como un agente humano." },
        { t: "Continuidad de contexto total", d: "Si un cliente chateó primero y luego llama, el agente sabe exactamente qué productos vio, qué preguntó y qué tiene en el carrito." },
        { t: "Misma inteligencia, diferente canal", d: "El mismo knowledge base, catálogo y personalidad de tu marca — ahora también por teléfono." },
        { t: "Analytics unificados", d: "Las interacciones de voz se registran junto a las del chat. Un solo dashboard para medir todo el impacto." },
      ],
      foot: "Disponible en planes Professional y Enterprise.",
    },
    vision: {
      eyebrow: "Visión IA",
      h: "Tu cliente manda una foto de su espacio. Kova le arma la compra.",
      lead: "Sube una foto de su living, su pieza o una inspiración que vio en Instagram. Kova analiza el estilo, la paleta y las proporciones del ambiente — y recomienda las piezas de tu catálogo que de verdad combinan. Como tener un asesor de interiores 24/7.",
      points: [
        { t: "Foto desde la cámara o la galería", d: "El cliente toca el clip, saca una foto al momento o elige una de su galería. Sin apps, sin fricción." },
        { t: "Entiende el espacio, no solo el objeto", d: "Kova lee estilo, colores y proporciones del ambiente para recomendar lo que realmente combina." },
        { t: "Recomienda desde TU catálogo", d: "Cruza lo que ve con tu inventario real y arma la selección con productos disponibles — no sugerencias genéricas." },
        { t: "De la foto al carrito", d: "Las piezas recomendadas se agregan al carrito en un toque. Ideal para muebles, deco e iluminación de alto ticket." },
      ],
      foot: "Incluido en el widget de Kova, sin configuración.",
    },
    verts: {
      eyebrow: "Verticales",
      h: "Pensado para tiendas de hogar premium",
      lead: "Donde cada venta es de alto ticket y el cliente lo piensa días antes de decidir.",
      items: [
        { label: "Muebles de diseño", before: "Tienda de sofás y comedores con ticket sobre $800.000. El cliente compara durante semanas antes de decidir.", after: "Kova resuelve dudas de medidas, telas y despacho al instante — y llama para cerrar la venta.", stat: "+32%", statl: "de cotizaciones que terminan en compra" },
        { label: "Deco e iluminación", before: "Catálogo de 1.500 piezas de diseño. El visitante no sabe qué combina con qué.", after: "Kova arma el ambiente completo y sube el ticket con piezas complementarias.", stat: "+28%", statl: "ticket promedio" },
        { label: "Terraza y muebles a medida", before: "Proyectos a medida con plazos de semanas. Muchos clientes cotizan y desaparecen.", after: "Kova hace seguimiento automático y agenda la visita o llamada de cierre.", stat: "30%", statl: "de cotizaciones frías recuperadas" },
      ],
      before: "Antes", after: "Con Kova",
    },
    how: {
      eyebrow: "Cómo funciona",
      h: "Tres pasos para empezar",
      lead: "Del catálogo al cierre, con inteligencia artificial.",
      steps: [
        { t: "Conecta tu tienda", d: "Instala Kova en tu Shopify o WooCommerce en minutos. Sincronización automática de catálogo con embeddings semánticos." },
        { t: "Personaliza tu asistente", d: "Configura colores, mensajes, tono de voz, idioma y comportamiento del AI. Se adapta a la identidad de tu marca." },
        { t: "Vende más con IA", d: "El asistente atiende a tus clientes 24/7: recomienda productos, gestiona el carrito y genera conversiones medibles." },
      ],
    },
    feats: {
      eyebrow: "Todo incluido",
      h: "Cada función, un solo objetivo: convertir",
      lead: "Diseñado para transformar visitantes que dudan en compradores que cierran.",
      items: [
        { t: "Encuentran lo que buscan", d: "Tu cliente escribe “un sofá que quepa en un living pequeño” y Kova entiende. No keywords, no filtros complicados." },
        { t: "El carrito se llena desde el chat", d: "El cliente pregunta, Kova recomienda y agrega al carrito en un solo paso. Menos clics, más compras completadas." },
        { t: "Se ve como tu marca", d: "Colores, avatar, tono de voz, idioma — todo se adapta a tu tienda. Tus clientes hablan con tu marca, no con un bot." },
        { t: "Sabes cuánto genera", d: "Revenue atribuido al AI, tasa de conversión, productos top. No adivinas — ves el impacto real en tu dashboard." },
        { t: "Llamadas cuando el chat no basta", d: "Si el cliente prefiere hablar, Kova lo llama con voz IA — con todo el contexto. Sin repetir, sin fricción." },
        { t: "Recomendaciones por correo", d: "Kova envía sugerencias personalizadas al inbox — productos relacionados, restock, ofertas. Sin que muevas un dedo." },
        { t: "Cotizaciones al instante", d: "Para B2B o tickets altos, Kova arma y envía la cotización dentro de la conversación. Lista para aprobar." },
        { t: "Agenda reuniones sola", d: "Cuando un cliente quiere una llamada o demo, Kova revisa tu calendario y agenda el slot ideal — sin idas y vueltas." },
      ],
    },
    cmp: {
      eyebrow: "Comparación",
      h: "¿Por qué elegir Kova?",
      lead: "Comparado con las alternativas más populares del mercado.",
      cols: ["Funcionalidad", "Kova", "Tidio", "Gorgias", "Intercom"],
      rows: [
        ["Chat IA", "y", "y", "y", "y"],
        ["Llamadas con voz IA", "y", "n", "n", "n"],
        ["Carrito integrado", "y", "Limitado", "Limitado", "Limitado"],
        ["Búsqueda semántica", "y", "Keywords", "Keywords", "Keywords"],
        ["Shopify + WooCommerce", "y", "Solo Shopify", "y", "n"],
        ["Español nativo", "y", "Limitado", "Limitado", "Limitado"],
        ["Emails con recomendaciones IA", "y", "Limitado", "Limitado", "Limitado"],
        ["Cotizaciones automáticas", "y", "n", "n", "n"],
        ["Agenda reuniones desde el chat", "y", "n", "n", "n"],
        ["Recomienda por foto (visión IA)", "y", "n", "n", "n"],
      ],
    },
    stats: {
      eyebrow: "Resultados reales",
      h: "Las primeras tiendas ya están vendiendo más",
      lead: "10% de conversión promedio. Más de 2.000 recomendaciones que terminaron en compra. Menos de 20 minutos de recomendación a checkout.",
      items: [{ b: "10%", s: "Conversión" }, { b: "2.195+", s: "Ventas asistidas" }, { b: "<20m", s: "A compra" }],
    },
    value: {
      eyebrow: "El valor",
      h: "Como tener un equipo de showroom completo",
      lead: "Un asesor de ventas, un experto en producto y un coordinador de despacho — armarlo por separado costaría esto cada mes.",
      rows: [
        { l: "Vendedor AI disponible 24/7", s: "vs contratar una persona", p: "$2,500/mes" },
        { l: "Búsqueda inteligente de productos", s: "vs implementación custom", p: "$800/mes" },
        { l: "Analytics de conversión con atribución", s: "vs herramientas separadas", p: "$400/mes" },
        { l: "Llamadas telefónicas con voz IA", s: "vs call center", p: "$600/mes" },
        { l: "Knowledge base + personalización total", s: "vs desarrollo a medida", p: "$300/mes" },
      ],
      totalk: "Valor total", total: "$4,600", totalper: "/mes",
      invk: "Tu inversión", inv: "desde $99/mes",
      foot: "Eso es un 96% de lo que costaría hacerlo por tu cuenta.",
    },
    pricing: {
      eyebrow: "Precio de lanzamiento — cupos limitados",
      h: "Recupera una venta de alto ticket y Kova ya se pagó",
      lead: "Cuando tu ticket promedio es de cientos de miles, una sola venta asistida cubre tu plan por meses.",
      monthly: "Mensual", annual: "Anual", save: "−20%",
      per: "USD/mes", popular: "Popular",
      plans: [
        { name: "Starter", was: "$149", now: "$99", feats: ["1.000 mensajes AI/mes", "Búsqueda semántica", "Gestión de carrito", "Emails con recomendaciones IA", "Cotizaciones automáticas", "Agenda reuniones desde el chat", "Analytics de conversión", "Branding personalizado"], cta: "Comenzar ahora", feat: false },
        { name: "Professional", was: "$349", now: "$299", feats: ["100 llamadas de voz/mes|NEW", "10.000 mensajes AI/mes", "Búsqueda semántica", "Gestión de carrito", "Emails con recomendaciones IA", "Cotizaciones automáticas", "Agenda reuniones desde el chat", "Soporte prioritario"], cta: "Elegir Professional", feat: true },
        { name: "Enterprise", was: "", now: "$599", feats: ["Llamadas de voz ilimitadas|NEW", "Mensajes ilimitados", "Todas las funcionalidades", "Acceso a API", "Soporte dedicado"], cta: "Contactar ventas", feat: false },
      ],
      foot: "Todos los planes incluyen 7 días de prueba. Precios en USD.",
    },
    guarantee: { eyebrow: "Sin riesgo", h: "Garantía de 30 días", lead: "Si en los primeros 30 días no ves un impacto real en tus conversiones, te devolvemos el 100% de tu dinero. Sin preguntas, sin letra chica. Creemos tanto en Kova que asumimos todo el riesgo por ti." },
    faq: {
      eyebrow: "Preguntas frecuentes",
      h: "Todo lo que necesitas saber",
      items: [
        { q: "¿Qué es Kova?", a: "Kova es un asistente de compras con inteligencia artificial que se instala en tu tienda online (Shopify o WooCommerce). Usa búsqueda semántica para entender lo que tus clientes necesitan, recomienda productos relevantes y gestiona el carrito — todo dentro de un chat conversacional." },
        { q: "¿Cómo se instala?", a: "En Shopify: instalación en 1 clic desde el Theme Editor (App Embeds). En WooCommerce: instala el plugin y completa el setup wizard. En ambos casos, el catálogo se sincroniza automáticamente. Todo el proceso toma menos de 5 minutos." },
        { q: "¿Cómo se miden las conversiones?", a: "Kova trackea cada recomendación hecha por el AI. Cuando un cliente compra un producto recomendado dentro de una ventana de atribución, se registra como conversión. El dashboard muestra métricas reales: recomendaciones, conversiones, revenue atribuido y top productos." },
        { q: "¿Puedo personalizar la apariencia del widget?", a: "Sí, completamente. Colores, avatar, mensajes de bienvenida, preguntas sugeridas, posición, tamaño, tema claro/oscuro — todo configurable desde el panel de administración sin tocar código." },
        { q: "¿En qué idiomas funciona?", a: "El asistente soporta múltiples idiomas. El idioma principal se configura por tienda y el AI responde en el idioma del cliente automáticamente." },
        { q: "¿Qué pasa con mis datos?", a: "Tus datos se almacenan de forma segura con aislamiento por tenant y row-level security. Las conversaciones, productos y configuraciones están protegidas y nunca se comparten entre tiendas." },
        { q: "¿Necesito conocimientos técnicos?", a: "No. La instalación, configuración del widget, carga de knowledge base y gestión de planes se hace completamente desde la interfaz visual. No se requiere código." },
        { q: "¿Puedo probar antes de pagar?", a: "Sí. Todos los planes incluyen 7 días de prueba con acceso completo a todas las funciones." },
      ],
    },
    bigcta: { eyebrow: "Empieza hoy", h: "Cada duda sin responder es una venta de alto ticket que se va a “pensarlo”", lead: "Mientras lees esto, alguien mira tu sofá, tu comedor o tu set de terraza — y tiene una duda que nadie responde. Kova la responde en segundos y llama para cerrar.", cta: "Activar mi vendedor IA", note: "Setup en 5 minutos · 7 días de prueba · Garantía de 30 días" },
    footer: { tag: "Asistente de ventas con IA para tiendas de hogar premium.", colP: "Producto", colR: "Recursos", colL: "Legal", product: ["Características", "Precios", "Demo"], resources: ["Documentación", "FAQ", "Shopify App Store", "WooCommerce"], legal: ["Términos de servicio", "Política de privacidad"], rights: "© 2026 Kova. Todos los derechos reservados." },
    widget: { online: "En línea", msg1: "¡Hola! ¿Buscas algo en particular?", msg2: "Sí, vi el Sofá Modular Roble", msg3: "¡Excelente elección! ¿Quieres medidas y telas disponibles?", msg4: "Prefiero hablar por teléfono", input: "Escribe un mensaje…", visionQ: "¿Qué sofá combina con mi living?", visionA: "Para tu estilo nórdico en tonos cálidos, te recomiendo:", p1: "Sofá Modular Roble", p1p: "$1.290.000", p2: "Lámpara de Pie Lino", p2p: "$189.000", calling: "Llamando", mute: "silenciar", keypad: "teclado", speaker: "altavoz", hBot1: "¡Hola! 👋 Soy tu asistente de compras. ¿En qué puedo ayudarte?", hMe1: "Busco un sofá para un living pequeño", hBot2: "¡Tengo la opción perfecta 🛋️", prod3: "Sofá Modular Roble · 3 cuerpos", prod3p: "$1.290.000", addCart: "Agregar al carrito", hBot3: "¿Quieres que te explique medidas y despacho por teléfono? 📞", reqCall: "Solicitar llamada" },
  },

  en: {
    nav: { features: "Features", how: "How it works", pricing: "Pricing", faq: "FAQ", login: "Log in", cta: "Get started" },
    hero: {
      eyebrow: "For premium home stores · high ticket",
      h1a: "Your best showroom seller,",
      h1em: "now 24/7",
      lead: "High-ticket buyers don't decide on impulse: they have questions about dimensions, materials and delivery. If no one answers instantly, they leave to “think about it” and never return. Kova advises over chat, recommends from your catalog and calls them on the phone to close the sale.",
      cta1: "Activate my showroom seller",
      cta2: "Watch demo",
      note: "5-minute setup · 7-day trial · Cancel anytime",
      chips: ["AI voice calls", "Built-in cart", "Recommendation emails", "Automatic quotes", "Books meetings", "Recommends by photo"],
    },
    logos: { title: "Integrates with the leading e-commerce platforms" },
    media: {
      bandA: { k: "The showroom, around the clock", t: "Every piece is a high-ticket decision" },
      galleryK: "The catalog",
      galleryT: "Design your customer wants to touch before buying",
      gallery: [{ k: "01", cap: "Designer furniture" }, { k: "02", cap: "Lighting" }, { k: "03", cap: "Decor & objects" }],
      bandB: { k: "The whole room", t: "Kova understands the space, not just the product" },
      bandC: { k: "From “let me think about it”", t: "…to checkout, in one conversation" },
    },
    voice: {
      eyebrow: "New · AI Voice",
      h: "Real phone calls with AI — with the full context",
      lead: "Kova doesn't just chat. Your assistant answers and makes real phone calls — not VoIP, not voice chat — to real numbers. And it does so with the entire conversation history. No repeating, no friction.",
      points: [
        { t: "Real inbound & outbound calls", d: "The voice agent answers and places calls to real phone numbers. Your customers call your store's number and Kova picks up — like a human agent." },
        { t: "Full context continuity", d: "If a customer chatted first and then calls, the agent knows exactly which products they saw, what they asked and what's in their cart." },
        { t: "Same intelligence, different channel", d: "The same knowledge base, catalog and brand personality — now over the phone too." },
        { t: "Unified analytics", d: "Voice interactions are logged alongside chat. One dashboard to measure the full impact." },
      ],
      foot: "Available on Professional and Enterprise plans.",
    },
    vision: {
      eyebrow: "AI Vision",
      h: "Your customer sends a photo of their space. Kova builds the order.",
      lead: "They upload a photo of their living room, their bedroom or an inspiration they saw on Instagram. Kova analyzes the style, palette and proportions of the space — and recommends the pieces from your catalog that truly match. Like having an interior advisor 24/7.",
      points: [
        { t: "Photo from camera or gallery", d: "The customer taps the clip, snaps a photo or picks one from their gallery. No apps, no friction." },
        { t: "Understands the space, not just the object", d: "Kova reads style, colors and proportions of the room to recommend what really fits." },
        { t: "Recommends from YOUR catalog", d: "It cross-references what it sees with your real inventory and builds the selection with available products — not generic suggestions." },
        { t: "From photo to cart", d: "Recommended pieces are added to the cart in one tap. Ideal for high-ticket furniture, decor and lighting." },
      ],
      foot: "Included in the Kova widget, no setup required.",
    },
    verts: {
      eyebrow: "Verticals",
      h: "Built for premium home stores",
      lead: "Where every sale is high-ticket and the customer thinks for days before deciding.",
      items: [
        { label: "Designer furniture", before: "Sofa and dining store with tickets over $800,000. Customers compare for weeks before deciding.", after: "Kova resolves questions about dimensions, fabrics and delivery instantly — and calls to close the sale.", stat: "+32%", statl: "of quotes that turn into purchases" },
        { label: "Decor & lighting", before: "Catalog of 1,500 designer pieces. The visitor doesn't know what matches what.", after: "Kova builds the complete look and raises the ticket with complementary pieces.", stat: "+28%", statl: "average ticket" },
        { label: "Outdoor & custom", before: "Custom projects with week-long lead times. Many customers quote and disappear.", after: "Kova follows up automatically and books the visit or closing call.", stat: "30%", statl: "of cold quotes recovered" },
      ],
      before: "Before", after: "With Kova",
    },
    how: {
      eyebrow: "How it works",
      h: "Three steps to start",
      lead: "From catalog to close, with artificial intelligence.",
      steps: [
        { t: "Connect your store", d: "Install Kova on your Shopify or WooCommerce in minutes. Automatic catalog sync with semantic embeddings." },
        { t: "Customize your assistant", d: "Set colors, messages, tone of voice, language and AI behavior. It adapts to your brand identity." },
        { t: "Sell more with AI", d: "The assistant serves your customers 24/7: recommends products, manages the cart and drives measurable conversions." },
      ],
    },
    feats: {
      eyebrow: "All included",
      h: "Every feature, one goal: convert",
      lead: "Designed to turn hesitating visitors into buyers who close.",
      items: [
        { t: "They find what they need", d: "Your customer types “a sofa that fits a small living room” and Kova gets it. No keywords, no complicated filters." },
        { t: "The cart fills from the chat", d: "The customer asks, Kova recommends and adds to cart in a single step. Fewer clicks, more completed purchases." },
        { t: "Looks like your brand", d: "Colors, avatar, tone of voice, language — all adapts to your store. Customers talk to your brand, not a bot." },
        { t: "You know what it earns", d: "AI-attributed revenue, conversion rate, top products. You don't guess — you see real impact on your dashboard." },
        { t: "Calls when chat isn't enough", d: "If the customer prefers to talk, Kova calls them with AI voice — with full context. No repeating, no friction." },
        { t: "Recommendations by email", d: "Kova sends personalized suggestions to the inbox — related products, restock, offers. Without lifting a finger." },
        { t: "Quotes in an instant", d: "For B2B or high tickets, Kova builds and sends the quote within the conversation. Ready to approve." },
        { t: "Books meetings on its own", d: "When a customer wants a call or demo, Kova checks your calendar and books the ideal slot — no back and forth." },
      ],
    },
    cmp: {
      eyebrow: "Comparison",
      h: "Why choose Kova?",
      lead: "Compared with the most popular alternatives on the market.",
      cols: ["Feature", "Kova", "Tidio", "Gorgias", "Intercom"],
      rows: [
        ["AI chat", "y", "y", "y", "y"],
        ["AI voice calls", "y", "n", "n", "n"],
        ["Built-in cart", "y", "Limited", "Limited", "Limited"],
        ["Semantic search", "y", "Keywords", "Keywords", "Keywords"],
        ["Shopify + WooCommerce", "y", "Shopify only", "y", "n"],
        ["Native Spanish", "y", "Limited", "Limited", "Limited"],
        ["AI recommendation emails", "y", "Limited", "Limited", "Limited"],
        ["Automatic quotes", "y", "n", "n", "n"],
        ["Books meetings from chat", "y", "n", "n", "n"],
        ["Recommends by photo (AI vision)", "y", "n", "n", "n"],
      ],
    },
    stats: {
      eyebrow: "Real results",
      h: "The first stores are already selling more",
      lead: "10% average conversion. Over 2,000 recommendations that ended in a purchase. Less than 20 minutes from recommendation to checkout.",
      items: [{ b: "10%", s: "Conversion" }, { b: "2,195+", s: "Assisted sales" }, { b: "<20m", s: "To purchase" }],
    },
    value: {
      eyebrow: "The value",
      h: "Like a full showroom team",
      lead: "A sales advisor, a product expert and a delivery coordinator — building it separately would cost this every month.",
      rows: [
        { l: "AI seller available 24/7", s: "vs hiring a person", p: "$2,500/mo" },
        { l: "Smart product search", s: "vs custom implementation", p: "$800/mo" },
        { l: "Conversion analytics with attribution", s: "vs separate tools", p: "$400/mo" },
        { l: "AI voice phone calls", s: "vs call center", p: "$600/mo" },
        { l: "Knowledge base + full customization", s: "vs custom development", p: "$300/mo" },
      ],
      totalk: "Total value", total: "$4,600", totalper: "/mo",
      invk: "Your investment", inv: "from $99/mo",
      foot: "That's 96% of what it would cost to do it on your own.",
    },
    pricing: {
      eyebrow: "Launch pricing — limited spots",
      h: "Recover one high-ticket sale and Kova has paid for itself",
      lead: "When your average ticket is in the hundreds of thousands, a single assisted sale covers your plan for months.",
      monthly: "Monthly", annual: "Annual", save: "−20%",
      per: "USD/mo", popular: "Popular",
      plans: [
        { name: "Starter", was: "$149", now: "$99", feats: ["1,000 AI messages/mo", "Semantic search", "Cart management", "AI recommendation emails", "Automatic quotes", "Books meetings from chat", "Conversion analytics", "Custom branding"], cta: "Get started", feat: false },
        { name: "Professional", was: "$349", now: "$299", feats: ["100 voice calls/mo|NEW", "10,000 AI messages/mo", "Semantic search", "Cart management", "AI recommendation emails", "Automatic quotes", "Books meetings from chat", "Priority support"], cta: "Choose Professional", feat: true },
        { name: "Enterprise", was: "", now: "$599", feats: ["Unlimited voice calls|NEW", "Unlimited messages", "All features", "API access", "Dedicated support"], cta: "Contact sales", feat: false },
      ],
      foot: "All plans include a 7-day trial. Prices in USD.",
    },
    guarantee: { eyebrow: "No risk", h: "30-day guarantee", lead: "If in the first 30 days you don't see real impact on your conversions, we refund 100% of your money. No questions, no fine print. We believe in Kova so much we take all the risk for you." },
    faq: {
      eyebrow: "Frequently asked questions",
      h: "Everything you need to know",
      items: [
        { q: "What is Kova?", a: "Kova is an AI shopping assistant that installs on your online store (Shopify or WooCommerce). It uses semantic search to understand what your customers need, recommends relevant products and manages the cart — all within a conversational chat." },
        { q: "How is it installed?", a: "On Shopify: 1-click install from the Theme Editor (App Embeds). On WooCommerce: install the plugin and complete the setup wizard. In both cases, the catalog syncs automatically. The whole process takes under 5 minutes." },
        { q: "How are conversions measured?", a: "Kova tracks every recommendation made by the AI. When a customer buys a recommended product within an attribution window, it's logged as a conversion. The dashboard shows real metrics: recommendations, conversions, attributed revenue and top products." },
        { q: "Can I customize the widget's appearance?", a: "Yes, completely. Colors, avatar, welcome messages, suggested questions, position, size, light/dark theme — all configurable from the admin panel without touching code." },
        { q: "What languages does it work in?", a: "The assistant supports multiple languages. The primary language is set per store and the AI responds in the customer's language automatically." },
        { q: "What about my data?", a: "Your data is stored securely with tenant isolation and row-level security. Conversations, products and settings are protected and never shared between stores." },
        { q: "Do I need technical knowledge?", a: "No. Installation, widget setup, knowledge base upload and plan management are done entirely from the visual interface. No code required." },
        { q: "Can I try before paying?", a: "Yes. All plans include a 7-day trial with full access to all features." },
      ],
    },
    bigcta: { eyebrow: "Start today", h: "Every unanswered question is a high-ticket sale that leaves to “think about it”", lead: "As you read this, someone is looking at your sofa, your dining set or your patio collection — with a question no one is answering. Kova answers in seconds and calls to close.", cta: "Activate my AI seller", note: "5-minute setup · 7-day trial · 30-day guarantee" },
    footer: { tag: "AI sales assistant for premium home stores.", colP: "Product", colR: "Resources", colL: "Legal", product: ["Features", "Pricing", "Demo"], resources: ["Documentation", "FAQ", "Shopify App Store", "WooCommerce"], legal: ["Terms of service", "Privacy policy"], rights: "© 2026 Kova. All rights reserved." },
    widget: { online: "Online", msg1: "Hi! Looking for something in particular?", msg2: "Yes, I saw the Oak Modular Sofa", msg3: "Great choice! Want dimensions and available fabrics?", msg4: "I'd rather talk on the phone", input: "Type a message…", visionQ: "What sofa matches my living room?", visionA: "For your warm-toned Nordic style, I recommend:", p1: "Oak Modular Sofa", p1p: "$1,290,000", p2: "Linen Floor Lamp", p2p: "$189,000", calling: "Calling", mute: "mute", keypad: "keypad", speaker: "speaker", hBot1: "Hi! 👋 I'm your shopping assistant. How can I help?", hMe1: "Looking for a sofa for a small living room", hBot2: "I've got the perfect option 🛋️", prod3: "Oak Modular Sofa · 3-seater", prod3p: "$1,290,000", addCart: "Add to cart", hBot3: "Want me to explain dimensions and delivery by phone? 📞", reqCall: "Request a call" },
  },
};

export type Content = (typeof KOVA)["es"] & { lang: Lang };
